name: compare_2way
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  getwidget: ^1.2.4
  flutter_icons: ^1.1.0
  provider: ^4.3.3
  moor: ^3.4.0
  sqlite3_flutter_libs: ^0.3.0
  path_provider: ^1.6.27
  path: ^1.7.0
  uuid: ^2.2.2
  fluttertoast: ^7.1.8
  flutter_slidable: ^0.5.7
  flutter_reorderable_list: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono: ^1.10.0+3
  moor_generator: ^3.3.1
  build_runner: ^1.10.1

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_image.png"
#  adaptive_icon_background: "#313131"
#  adaptive_icon_foreground: "assets/images/icon_image.png"


dependency_overrides:
  analyzer: ^0.39.14


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#fonts:
#     - family: Hiragino Kaku Gothic w3
#       fonts:
#         - asset: assets/fonts/
#     - family: Hiragino Kaku Gothic w6
#       fonts:
#        - asset: assets/fonts/
#     - family: SF Pro Display Medium
#       fonts:
#         - asset: assets/fonts/
#           weight: 700
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
