name: compare_2way
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  getwidget: ^3.0.1
  flutter_icons_null_safety: ^1.1.0
  provider: ^6.0.5
  moor: ^4.6.1+1
  sqlite3_flutter_libs: ^0.5.12
  path_provider: ^2.0.11
  path: ^1.8.2
  uuid: ^3.0.7
  fluttertoast: ^8.1.2
  flutter_slidable: ^2.0.0
  flutter_reorderable_list: ^1.2.0
  settings_ui: ^2.0.2
  flutter_launcher_icons: ^0.11.0
  webview_flutter: ^4.0.1
  app_review: ^2.1.2+1
  flutter_email_sender: ^5.2.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono: ^1.20.1
  moor_generator: ^4.6.0+1
  build_runner: ^2.3.3


flutter_icons:
  android: true
#  "launcher_icon"
  ios: true
  image_path: "assets/images/icon_image.png"

#adaptive_icon使うと丸くなってforegroundの画像も大きすぎる
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_image.png"


#dependency_overrides:
#  analyzer: ^0.39.14


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#fonts:
#     - family: Hiragino Kaku Gothic w3
#       fonts:
#         - asset: assets/fonts/
#     - family: Hiragino Kaku Gothic w6
#       fonts:
#        - asset: assets/fonts/
#     - family: SF Pro Display Medium
#       fonts:
#         - asset: assets/fonts/
#           weight: 700
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
